INSERT INTO option VALUES('AMV', 'Logo version latérale, peint en argent', 204);
INSERT INTO option VALUES('AMW', 'Logo version latérale, peint en or', 204);
INSERT INTO option VALUES('AAV', 'Version version peinte en peinture extérieure - Porsche Exclusive Manufaktur', 234);
INSERT INTO option VALUES('QE1', 'Pack Rangement', 234);
INSERT INTO option VALUES('2V4', 'Purificateur d''air', 281);
INSERT INTO option VALUES('GT6', 'Pack d''accent en peinture extérieure - Porsche Exclusive Manufaktur', 292);
INSERT INTO option VALUES('6E3', 'Inscription du modèle sur le couvercle de la console centrale de la boîte de rangement - Porsche Exclusive Manufaktur'	,    304);
INSERT INTO option VALUES('6E7', 'Logo «PORSCHE» sur le couvercle de la console centrale de la boîte de rangement - Porsche Exclusive Manufaktur',	 304);	
INSERT INTO option VALUES('AFL', 'Porte-clés de voiture (2) peints (couleur carrosserie) et étui à clés en cuir', 362);
INSERT INTO option VALUES('AGA', 'Porte-documents en cuir', 374);
INSERT INTO option VALUES('NJ1', 'Station d''accueil pour charger', 409);
INSERT INTO option VALUES('AFP', 'Porte-clés et étui à clés en cuir - Porsche Exclusive Manufaktur', 462);
INSERT INTO option VALUES('VW1', 'Vitres teintées', 491);
INSERT INTO option VALUES('JH1', 'Écran pour passager (avant)', 1005);
INSERT INTO option VALUES('NW2', 'Connexion du chargeur mobile', 106);